In [38]:
import pandas as pd
pd.set_option('display.float_format', lambda x: '%.2f' % x)

In [30]:
data = {
    "date": ["2022-01-01", "2022-01-02", "2022-01-03", "2022-01-04", "2022-01-05"],
    "close": [150.0, 152.0, 153.0, 154.0, 155.0],
    "volume": [1000, 1200, 1300, 1250, 1350],
}

df = pd.DataFrame(data)
df

         date  close  volume
0  2022-01-01  150.0    1000
1  2022-01-02  152.0    1200
2  2022-01-03  153.0    1300
3  2022-01-04  154.0    1250
4  2022-01-05  155.0    1350

In [35]:
print(df.iloc[2][["date", "close"]])

date     2022-01-03
close         153.0
Name: 2, dtype: object

In [36]:
df = pd.read_csv("APPL_1D.csv")
df

,time,open,high,low,close,volume,Volume MA
0,1320240600,12.144762,12.155382,11.993595,12.063406,328255052.0,5.656631e+08
1,1320327000,12.113800,12.245232,12.001184,12.235220,441524796.0,5.471102e+08
2,1320413400,12.203650,12.246448,12.116527,12.149313,302228240.0,5.354408e+08
3,1320676200,12.139294,12.142028,12.024551,12.133831,270274636.0,5.268289e+08
4,1320762600,12.209111,12.384869,12.189383,12.331139,400439768.0,5.165667e+08
...,...,...,...,...,...,...,...
2915,1686058200,179.965000,180.120000,177.430000,179.210000,64848374.0,5.881860e+07
2916,1686144600,178.440000,181.210000,177.320000,177.820000,61944615.0,5.964949e+07
2917,1686231000,177.895000,180.840000,177.460000,180.570000,50214881.0,5.947401e+07
2918,1686317400,181.500000,182.230000,180.630000,180.960000,48899973.0,5.944327e+07
2919,1686576600,181.270000,NaN,NaN,NaN,NaN,NaN

In [41]:
df.describe()

               time    open    high     low   close        volume    Volume MA
count       2920.00 2920.00 2919.00 2919.00 2919.00       2919.00      2919.00
mean  1503502927.40   59.74   60.38   59.07   59.75  200558014.51 202115717.49
std    105701072.41   51.30   51.90   50.66   51.31  171035615.19 148989947.08
min   1320240600.00    0.00   11.27   11.03   11.04   35195860.00  50684940.65
25%   1412062200.00   21.83   22.09   21.62   21.85   91766241.00 101733696.10
50%   1503451800.00   36.49   36.72   36.18   36.58  137148384.00 138776456.20
75%   1595057400.00   93.83   94.55   92.27   93.84  247976166.00 250714603.00
max   1686576600.00  182.63  184.95  180.63  180.96 1506113440.00 807241634.00

In [44]:
df = df.drop('Volume MA', axis=1)
df

            time   open   high    low  close       volume
0     1320240600  12.14  12.16  11.99  12.06 328255052.00
1     1320327000  12.11  12.25  12.00  12.24 441524796.00
2     1320413400  12.20  12.25  12.12  12.15 302228240.00
3     1320676200  12.14  12.14  12.02  12.13 270274636.00
4     1320762600  12.21  12.38  12.19  12.33 400439768.00
...          ...    ...    ...    ...    ...          ...
2915  1686058200 179.97 180.12 177.43 179.21  64848374.00
2916  1686144600 178.44 181.21 177.32 177.82  61944615.00
2917  1686231000 177.90 180.84 177.46 180.57  50214881.00
2918  1686317400 181.50 182.23 180.63 180.96  48899973.00
2919  1686576600 181.27    NaN    NaN    NaN          NaN

[2920 rows x 6 columns]

In [47]:
df.loc[df['high'].isnull()]

            time   open  high  low  close  volume
2919  1686576600 181.27   NaN  NaN    NaN     NaN

In [48]:
df.drop(2919)

            time   open   high    low  close       volume
0     1320240600  12.14  12.16  11.99  12.06 328255052.00
1     1320327000  12.11  12.25  12.00  12.24 441524796.00
2     1320413400  12.20  12.25  12.12  12.15 302228240.00
3     1320676200  12.14  12.14  12.02  12.13 270274636.00
4     1320762600  12.21  12.38  12.19  12.33 400439768.00
...          ...    ...    ...    ...    ...          ...
2914  1685971800 182.63 184.95 178.03 179.58 121946497.00
2915  1686058200 179.97 180.12 177.43 179.21  64848374.00
2916  1686144600 178.44 181.21 177.32 177.82  61944615.00
2917  1686231000 177.90 180.84 177.46 180.57  50214881.00
2918  1686317400 181.50 182.23 180.63 180.96  48899973.00

[2919 rows x 6 columns]

In [49]:
df["time"] = pd.to_datetime(df["time"], unit='s')
print(df["time"])

0      2011-11-02 13:30:00
1      2011-11-03 13:30:00
2      2011-11-04 13:30:00
3      2011-11-07 14:30:00
4      2011-11-08 14:30:00
               ...
2915   2023-06-06 13:30:00
2916   2023-06-07 13:30:00
2917   2023-06-08 13:30:00
2918   2023-06-09 13:30:00
2919   2023-06-12 13:30:00
Name: time, Length: 2920, dtype: datetime64[s]

In [50]:
df.loc[df["open"] == 0]

                   time  open  high   low  close       volume
985 2015-10-05 13:30:00  0.00 25.31 24.78  25.17 208258972.00

In [53]:
df["low_high_avg"] = (df["low"] + df["high"]) / 2
df["low_high_avg"]

0       12.07
1       12.12
2       12.18
3       12.08
4       12.29
        ...
2915   178.78
2916   179.26
2917   179.15
2918   181.43
2919      NaN
Name: low_high_avg, Length: 2920, dtype: float64

In [ ]:
df.loc[df["open"] == 0, "open"] = df["low_high_avg"]
df.loc[df["open"] == 0]